// This file is generated by `supabase gen types typescript`.
// Run: supabase gen types typescript --project-id <project-id> > src/lib/supabase/database.types.ts
// It is intentionally excluded from version control and kept as a stub locally.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
    CompositeTypes: Record<string, unknown>;
  };
};
